### ISSUE TITLE
Issues with `version()` and `supported_languages()`

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-python#141]
I run the following code and get:

```python
import bblfsh
client = bblfsh.BblfshClient("0.0.0.0:9432")

print(client.version())
elapsed {
}
version: "v2.11.0"
build {
  seconds: -62135596800
}

print(client.supported_languages())
[name: "JavaScript"
language: "javascript"
version: "dev-adcd1b4"
status: "beta"
features: "ast"
features: "uast"
features: "roles"
]
```

The version string has a negative number of seconds and empty "elapsed".

The javascript driver version is reported to be "dev-adcd1b4", which does not help to check that it is 1.2.0 (which we strictly require since the newer versions do not work for us).

**Comment by juanjux** [comment]
There are several issues here, neither of those culprit of the poor Python client :)

- Missing elapsed and negative seconds seems to be a problem with the `VersionResponse` implementation in `bblfshd` since the returned value is directly the one from calling `VersionRequest` on the client without any added code.

- Bad version for the Javascript driver, seems to be a problem with either the Javascript driver or the SDK.

I'll confirm that the problems are in bblfshd/javascript-driver/sdk and reopen in the right projects adding you to the CC.

**Comment by juanjux** [comment]
I've fixed the "elapsed" problem, as expected [it was a bug in bblfshd](https://github.com/bblfsh/bblfshd/pull/233), looking now at why the elapsed time is empty for that request type which won't be far from that other critter.

**Comment by juanjux** [comment]
Closing this, I'll open an issue for the javascript driver version.
